name: the_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.3
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  stacked_shared: any
  path: any
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  objectbox_generator: any

flutter:
  uses-material-design: true

